### ISSUE TITLE
Feature Request: change `close-issue-reason` to `not_planned`

### ISSUE THREAD

**Issue by joey-ma** [roots/issue-closer-action#3]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

I appreciate how **Issue auto-closer** aims to close issues that did not follow the issue templates, but I think it would make sense to close it _as_ `not_planned` instead of `completed` (which kind of contradicts with the `issue-close-message`: "this issue was automatically closed because it did not follow the issue template").

#### Why are we doing this?
Improve clarity and consistency; i.e., the issue is closed _not_ because it is **completed**, but it is closed because it is _**not planned**_.

![image](https://user-images.githubusercontent.com/86270711/209402568-c269b685-2e09-44ae-b424-69d97a3374b5.png)
![image](https://user-images.githubusercontent.com/86270711/209403731-299717af-edc3-4d59-a8ff-2dff5fd12ecb.png)

#### What use cases does it support?

I think it improves consistency for original intention of **issue-closer-action**. Another perspective is that it can also introduce flexibility if it is added as an optional input, as not required and with a default value of `not_planned`.

#### What is the expected outcome?

![image](https://user-images.githubusercontent.com/86270711/209403798-7d30d76a-753d-48f9-908b-791edb8d82eb.png)

```yml
    steps:
    - name: Autoclose issues that did not follow issue template
      uses: roots/issue-closer@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        close-issue-reason: not_planned 
        # makes more sense than `completed` 
        # and introduces flexibility should user wants to change it
```

#### Potential conflicts / foreseeable issues

None, except to add this info in the README.md / documentation.

### Additional Context

On a side note, I am seeing this in warning in Annotations. I'm hesitant to turn this into another issue, though. Please let me know if I should.

**autoclose**
```
Node.js 12 actions are deprecated. For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-
actions-will-begin-running-on-node16-instead-of-node12/. 
Please update the following actions to use Node.js 16: 
roots/issue-closer@v1.1
```

Not sure how I can confirm running on node16 would not introduce bugs, but I believe Node.js 18 is now out and node12 does seem a bit behind. Will you update this as well?
